const express = require('express');
const router = express.Router();
const summaryController = require('../controllers/summaryController');
const auth = require('../middleware/auth');
router.use(auth);
router.get('/monthly', summaryController.getMonthlySummary);
router.get('/', summaryController.getSummaryByDateRange);
router.get('/alerts', summaryController.getBudgetAlerts);
router.get('/overview', summaryController.getOverview);
module.exports = router;